In [ ]:
import numpy as np
import pandas as pd

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [ ]:
data = {
    "text": [
        "I love machine learning",
        "I love deep learning",
        "I love data science",
        "I love artificial intelligence",
        "I study machine learning",
        "I study deep learning",
        "I study data science",
        "I study artificial intelligence",
        "I learn machine learning",
        "I learn deep learning",
        "I learn data science",
        "I learn artificial intelligence",
        "I enjoy machine learning",
        "I enjoy deep learning",
        "I enjoy data science",
        "I enjoy artificial intelligence",
        "machine learning is useful",
        "machine learning is powerful",
        "machine learning is interesting",
        "machine learning is important",
        "machine learning is practical",
        "machine learning is popular",
        "machine learning is growing",
        "machine learning is helpful",
        "deep learning is useful",
        "deep learning is powerful",
        "deep learning is interesting",
        "deep learning is important",
        "deep learning is practical",
        "deep learning is popular",
        "deep learning is growing",
        "deep learning is helpful",
        "data science is useful",
        "data science is powerful",
        "data science is interesting",
        "data science is important",
        "data science is practical",
        "data science is popular",
        "data science is growing",
        "data science is helpful",
        "artificial intelligence is useful",
        "artificial intelligence is powerful",
        "artificial intelligence is interesting",
        "artificial intelligence is important",
        "artificial intelligence is practical",
        "artificial intelligence is popular",
        "artificial intelligence is growing",
        "artificial intelligence is helpful",
        "python is useful for data science",
        "python is popular for machine learning",
        "python is important for data science",
        "python is powerful for machine learning",
        "python is useful for artificial intelligence",
        "python is popular for deep learning",
        "python helps with data science",
        "python helps with machine learning",
        "python helps with deep learning",
        "python helps with artificial intelligence",
        "data is important for machine learning",
        "data is useful for data science",
        "data is important for deep learning",
        "data is useful for artificial intelligence",
        "good data improves machine learning",
        "good data improves deep learning",
        "good data improves data science",
        "good data improves artificial intelligence",
        "models learn from data",
        "models learn from examples",
        "models learn from training data",
        "machine learning models learn patterns",
        "deep learning models learn patterns",
        "data science uses data",
        "data science uses statistics",
        "data science uses python",
        "data science uses machine learning",
        "machine learning uses data",
        "machine learning uses algorithms",
        "machine learning uses statistics",
        "machine learning uses python",
        "deep learning uses neural networks",
        "deep learning uses large datasets",
        "deep learning uses python",
        "deep learning uses machine learning",
        "neural networks learn patterns",
        "neural networks learn from data",
        "neural networks are powerful",
        "neural networks are useful",
        "neural networks are important",
        "training improves the model",
        "training improves model accuracy",
        "more data improves the model",
        "more examples improve learning",
        "testing evaluates the model",
        "validation checks the model",
        "accuracy measures model performance",
        "loss measures model error",
        "the model predicts new data",
        "the model learns from examples",
        "the model learns useful patterns",
        "the model predicts the next word",
        "the RNN learns word patterns",
        "the RNN predicts the next word",
        "the RNN generates new words",
        "the RNN learns from sequences",
        "the RNN remembers previous words",
        "the RNN processes text sequences",
        "word prediction uses sequences",
        "word generation uses sequences",
        "language models predict words",
        "language models learn patterns",
        "learning machine learning is fun",
        "learning data science is fun",
        "learning deep learning is fun",
        "learning artificial intelligence is fun"
    ]
}

df = pd.DataFrame(data)

print("Number of sentences:", len(df))
print("\nFirst 10 sentences:")
print(df.head(10))

Number of sentences: 114

First 10 sentences:
                              text
0          I love machine learning
1             I love deep learning
2              I love data science
3   I love artificial intelligence
4         I study machine learning
5            I study deep learning
6             I study data science
7  I study artificial intelligence
8         I learn machine learning
9            I learn deep learning


In [ ]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(df["text"])

word_index = tokenizer.word_index
total_words = len(word_index) + 1

print("Word Index:")
print(word_index)

print("\nTotal words:", total_words)

Word Index:
{'learning': 1, 'is': 2, 'data': 3, 'machine': 4, 'deep': 5, 'science': 6, 'artificial': 7, 'intelligence': 8, 'i': 9, 'the': 10, 'uses': 11, 'python': 12, 'learn': 13, 'model': 14, 'useful': 15, 'for': 16, 'important': 17, 'improves': 18, 'models': 19, 'powerful': 20, 'popular': 21, 'from': 22, 'patterns': 23, 'neural': 24, 'networks': 25, 'rnn': 26, 'word': 27, 'love': 28, 'study': 29, 'enjoy': 30, 'interesting': 31, 'practical': 32, 'growing': 33, 'helpful': 34, 'helps': 35, 'with': 36, 'good': 37, 'learns': 38, 'sequences': 39, 'fun': 40, 'examples': 41, 'training': 42, 'are': 43, 'predicts': 44, 'words': 45, 'statistics': 46, 'accuracy': 47, 'more': 48, 'measures': 49, 'new': 50, 'next': 51, 'language': 52, 'algorithms': 53, 'large': 54, 'datasets': 55, 'improve': 56, 'testing': 57, 'evaluates': 58, 'validation': 59, 'checks': 60, 'performance': 61, 'loss': 62, 'error': 63, 'generates': 64, 'remembers': 65, 'previous': 66, 'processes': 67, 'text': 68, 'prediction': 69,

In [ ]:
WINDOW_SIZE = 3

print("Window size:", WINDOW_SIZE)

Window size: 3


Cell 5 — Create input and target pairs

In [ ]:
X = []
y = []

for sentence in df["text"]:
    words = sentence.lower().split()

    for i in range(len(words) - WINDOW_SIZE):
        input_words = words[i:i + WINDOW_SIZE]
        target_word = words[i + WINDOW_SIZE]

        X.append(input_words)
        y.append(target_word)

print("Number of samples:", len(X))

print("\nFirst 10 input-target pairs:")

for i in range(10):
    print(X[i], "->", y[i])

Number of samples: 167

First 10 input-target pairs:
['i', 'love', 'machine'] -> learning
['i', 'love', 'deep'] -> learning
['i', 'love', 'data'] -> science
['i', 'love', 'artificial'] -> intelligence
['i', 'study', 'machine'] -> learning
['i', 'study', 'deep'] -> learning
['i', 'study', 'data'] -> science
['i', 'study', 'artificial'] -> intelligence
['i', 'learn', 'machine'] -> learning
['i', 'learn', 'deep'] -> learning


Cell 6 — Convert the words to numbers

In [ ]:
X_numbers = []

for sequence in X:
    X_numbers.append([word_index[word] for word in sequence])

y_numbers = [word_index[word] for word in y]

X_numbers = np.array(X_numbers)
y_numbers = np.array(y_numbers)

print("X shape:", X_numbers.shape)
print("y shape:", y_numbers.shape)

print("\nFirst 10 X:")
print(X_numbers[:10])

print("\nFirst 10 y:")
print(y_numbers[:10])

X shape: (167, 3)
y shape: (167,)

First 10 X:
[[ 9 28  4]
 [ 9 28  5]
 [ 9 28  3]
 [ 9 28  7]
 [ 9 29  4]
 [ 9 29  5]
 [ 9 29  3]
 [ 9 29  7]
 [ 9 13  4]
 [ 9 13  5]]

First 10 y:
[1 1 6 8 1 1 6 8 1 1]


In [ ]:
print("X shape:", X_numbers.shape)
print("y shape:", y_numbers.shape)

print("\nOne training example:")
print("Input:", X_numbers[0])
print("Target:", y_numbers[0])

X shape: (167, 3)
y shape: (167,)

One training example:
Input: [ 9 28  4]
Target: 1


In [ ]:
model = Sequential()

model.add(Embedding(
    input_dim=total_words,
    output_dim=64,
    input_length=WINDOW_SIZE
))

model.add(SimpleRNN(
    128,
    activation='tanh'
))

model.add(Dense(
    total_words,
    activation='softmax'
))

model.summary()

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("Model compiled successfully.")

Model compiled successfully.


In [ ]:
history = model.fit(
    X_numbers,
    y_numbers,
    epochs=100,
    verbose=0
)

print("Training complete.")

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.0898 - loss: 4.2423
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3234 - loss: 4.1235 
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2934 - loss: 3.9807 
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2635 - loss: 3.7589 
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2096 - loss: 3.4467 
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2096 - loss: 3.1335 
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1916 - loss: 2.8818 
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2096 - loss: 2.6601 
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2754 - loss: 2.4462 
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3413 - loss: 2.2609 
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4072 - loss: 2.1238 
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4431 - loss

In [ ]:
def predict_next_word(seed_text):
    words = seed_text.lower().split()

    # Take the last 3 words
    words = words[-WINDOW_SIZE:]

    # Convert words to numbers
    sequence = [word_index[word] for word in words]

    # Add batch dimension
    sequence = np.array([sequence])

    # Predict
    prediction = model.predict(sequence, verbose=0)

    # Get word with highest probability
    predicted_index = np.argmax(prediction[0])

    # Convert number back to word
    for word, index in word_index.items():
        if index == predicted_index:
            return word

In [ ]:
seed_text = "I love"

predicted_word = predict_next_word(seed_text)

print("Input:", seed_text)
print("Predicted next word:", predicted_word)

Input: I love
Predicted next word: learning


Cell 13 — Generate multiple words

In [ ]:
def generate_text(seed_text, num_words):
    generated_text = seed_text

    for _ in range(num_words):
        next_word = predict_next_word(generated_text)
        generated_text += " " + next_word

    return generated_text

Cell 14 — Generate text

In [ ]:
seed_text = "I love"

generated = generate_text(seed_text, 1)

print("Generated text:")
print(generated)

Generated text:
I love study


In [ ]:
seeds = [
    "I love machine",
    "I study data",
    "deep learning is",
    "machine learning is",
    "the RNN predicts"
]

for seed in seeds:
    print(seed, "→", generate_text(seed, 3))

I love machine → I love machine learning is useful
I study data → I study data science the model
deep learning is → deep learning is practical for machine
machine learning is → machine learning is useful for artificial
the RNN predicts → the RNN predicts the next word


window size=4

In [ ]:
WINDOW_SIZE = 5

print("New window size:", WINDOW_SIZE)

New window size: 5


In [ ]:
X = []
y = []

for sentence in df["text"]:
    words = sentence.lower().split()

    for i in range(len(words) - WINDOW_SIZE):
        input_words = words[i:i + WINDOW_SIZE]
        target_word = words[i + WINDOW_SIZE]

        X.append(input_words)
        y.append(target_word)

print("Number of samples:", len(X))

for i in range(10):
    print(X[i], "->", y[i])

Number of samples: 12
['python', 'is', 'useful', 'for', 'data'] -> science
['python', 'is', 'popular', 'for', 'machine'] -> learning
['python', 'is', 'important', 'for', 'data'] -> science
['python', 'is', 'powerful', 'for', 'machine'] -> learning
['python', 'is', 'useful', 'for', 'artificial'] -> intelligence
['python', 'is', 'popular', 'for', 'deep'] -> learning
['data', 'is', 'important', 'for', 'machine'] -> learning
['data', 'is', 'useful', 'for', 'data'] -> science
['data', 'is', 'important', 'for', 'deep'] -> learning
['data', 'is', 'useful', 'for', 'artificial'] -> intelligence


In [ ]:
X_numbers = []

for sequence in X:
    X_numbers.append([word_index[word] for word in sequence])

y_numbers = [word_index[word] for word in y]

X_numbers = np.array(X_numbers)
y_numbers = np.array(y_numbers)

print("X shape:", X_numbers.shape)
print("y shape:", y_numbers.shape)

print("\nFirst 5 X:")
print(X_numbers[:5])

print("\nFirst 5 y:")
print(y_numbers[:5])

X shape: (12, 5)
y shape: (12,)

First 5 X:
[[12  2 15 16  3]
 [12  2 21 16  4]
 [12  2 17 16  3]
 [12  2 20 16  4]
 [12  2 15 16  7]]

First 5 y:
[6 1 6 1 8]


In [ ]:
model = Sequential()

model.add(Embedding(
    input_dim=total_words,
    output_dim=64
))

model.add(SimpleRNN(
    128,
    activation='tanh'
))

model.add(Dense(
    total_words,
    activation='softmax'
))

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("Model compiled successfully.")

Model compiled successfully.


In [ ]:
history = model.fit(
    X_numbers,
    y_numbers,
    epochs=200,
    verbose=0
)

print("Training complete.")

Training complete.


In [ ]:
def predict_next_word(seed_text):
    words = seed_text.lower().split()

    # Take the last WINDOW_SIZE words
    words = words[-WINDOW_SIZE:]

    # Convert words to numbers
    sequence = [word_index[word] for word in words]

    # Add batch dimension
    sequence = np.array([sequence])

    # Predict probabilities
    prediction = model.predict(sequence, verbose=0)[0]

    # Do not choose the same word as the last word
    last_word = words[-1]
    last_word_index = word_index[last_word]
    prediction[last_word_index] = 0

    # Convert probabilities into a proper distribution
    prediction = prediction / np.sum(prediction)

    # Randomly select based on probabilities
    predicted_index = np.random.choice(
        len(prediction),
        p=prediction
    )

    # Convert number back to word
    for word, index in word_index.items():
        if index == predicted_index:
            return word

In [ ]:
seed_text = "I love machine learning"

predicted_word = predict_next_word(seed_text)

print("Input:", seed_text)
print("Predicted next word:", predicted_word)

Input: I love machine learning
Predicted next word: word


In [ ]:
def generate_text(seed_text, num_words):
    generated_text = seed_text

    for _ in range(num_words):
        next_word = predict_next_word(generated_text)
        generated_text += " " + next_word

    return generated_text

In [ ]:
seed_text = "I love learning"

generated = generate_text(seed_text, 3)

print("Generated text:")
print(generated)

Generated text:
I love learning more error science


In [ ]:
WINDOW_SIZE = 3

X_backward = []
y_backward = []

for sentence in df["text"]:
    words = sentence.lower().split()

    # Reverse the sentence
    words = words[::-1]

    for i in range(len(words) - WINDOW_SIZE):
        input_words = words[i:i + WINDOW_SIZE]
        target_word = words[i + WINDOW_SIZE]

        X_backward.append(input_words)
        y_backward.append(target_word)

print("Number of backward samples:", len(X_backward))

for i in range(min(10, len(X_backward))):
    print(X_backward[i], "->", y_backward[i])

Number of backward samples: 167
['learning', 'machine', 'love'] -> i
['learning', 'deep', 'love'] -> i
['science', 'data', 'love'] -> i
['intelligence', 'artificial', 'love'] -> i
['learning', 'machine', 'study'] -> i
['learning', 'deep', 'study'] -> i
['science', 'data', 'study'] -> i
['intelligence', 'artificial', 'study'] -> i
['learning', 'machine', 'learn'] -> i
['learning', 'deep', 'learn'] -> i


In [ ]:
X_backward_numbers = []

for sequence in X_backward:
    X_backward_numbers.append(
        [word_index[word] for word in sequence]
    )

y_backward_numbers = [
    word_index[word] for word in y_backward
]

X_backward_numbers = np.array(X_backward_numbers)
y_backward_numbers = np.array(y_backward_numbers)

print("X shape:", X_backward_numbers.shape)
print("y shape:", y_backward_numbers.shape)

X shape: (167, 3)
y shape: (167,)


In [ ]:
backward_model = Sequential()

backward_model.add(
    Embedding(
        input_dim=total_words,
        output_dim=64
    )
)

backward_model.add(
    SimpleRNN(
        128,
        activation="tanh"
    )
)

backward_model.add(
    Dense(
        total_words,
        activation="softmax"
    )
)

backward_model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

backward_model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_3 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
WINDOW_SIZE = 3

X_backward = []
y_backward = []

for sentence in df["text"]:
    words = sentence.lower().split()
    words = words[::-1]

    for i in range(len(words) - WINDOW_SIZE):
        X_backward.append(words[i:i + WINDOW_SIZE])
        y_backward.append(words[i + WINDOW_SIZE])

print("Number of samples:", len(X_backward))

for i in range(min(10, len(X_backward))):
    print(X_backward[i], "->", y_backward[i])

Number of samples: 167
['learning', 'machine', 'love'] -> i
['learning', 'deep', 'love'] -> i
['science', 'data', 'love'] -> i
['intelligence', 'artificial', 'love'] -> i
['learning', 'machine', 'study'] -> i
['learning', 'deep', 'study'] -> i
['science', 'data', 'study'] -> i
['intelligence', 'artificial', 'study'] -> i
['learning', 'machine', 'learn'] -> i
['learning', 'deep', 'learn'] -> i


In [ ]:
X_backward_numbers = []

for sequence in X_backward:
    X_backward_numbers.append(
        [word_index[word] for word in sequence]
    )

y_backward_numbers = [
    word_index[word] for word in y_backward
]

X_backward_numbers = np.array(X_backward_numbers)
y_backward_numbers = np.array(y_backward_numbers)

print("X shape:", X_backward_numbers.shape)
print("y shape:", y_backward_numbers.shape)

X shape: (167, 3)
y shape: (167,)


In [ ]:
backward_model = Sequential([
    Embedding(
        input_dim=total_words,
        output_dim=64
    ),

    SimpleRNN(
        128,
        activation="tanh"
    ),

    Dense(
        total_words,
        activation="softmax"
    )
])

backward_model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

backward_model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history_backward = backward_model.fit(
    X_backward_numbers,
    y_backward_numbers,
    epochs=100,
    verbose=0
)

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.1377 - loss: 4.2385    
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4731 - loss: 4.0821 
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4850 - loss: 3.8782 
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4431 - loss: 3.5343
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.3533 - loss: 3.0544
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2695 - loss: 2.6657 
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3713 - loss: 2.4396 
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4311 - loss: 2.2321 
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5030 - loss: 2.0036
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5749 - loss: 1.8200
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6048 - loss: 1.6472
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5988 -

In [ ]:
def predict_previous_word(next_words):

    words = next_words.lower().split()

    # Take exactly the last 3 words
    words = words[:WINDOW_SIZE]

    sequence = [
        word_index[word]
        for word in words
    ]

    sequence = np.array([sequence])

    prediction = backward_model.predict(
        sequence,
        verbose=0
    )[0]

    predicted_index = np.argmax(prediction)

    for word, index in word_index.items():
        if index == predicted_index:
            return word

In [ ]:
print("machine:", word_index.get("machine"))
print("learning:", word_index.get("learning"))
print("because:", word_index.get("because"))

machine: 4
learning: 1
because: None


In [ ]:
test_words = X_backward[0]

print("Valid 3 words:")
print(test_words)

print("Actual previous word:")
print(y_backward[0])

Valid 3 words:
['learning', 'machine', 'love']
Actual previous word:
i


In [ ]:
next_words = " ".join(X_backward[0])

previous_word = predict_previous_word(next_words)

print("Next 3 words:", next_words)
print("Actual previous word:", y_backward[0])
print("Predicted previous word:", previous_word)

Next 3 words: learning machine love
Actual previous word: i
Predicted previous word: i


In [ ]:
next_words = " learning love"

previous_word = predict_previous_word(next_words)

print("Next 3 words:", next_words)
print("Predicted previous word:", previous_word)

Next 3 words:  learning love
Predicted previous word: i
